/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Authors: (auto-generated by AI assistant)
 *
 */

package org.rumbledb.runtime.functions.arrays;

import org.rumbledb.runtime.plan.RuntimePlan;


import java.io.Serial;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.rumbledb.api.Item;
import org.rumbledb.context.DynamicContext;
import org.rumbledb.context.RuntimeStaticContext;
import org.rumbledb.exceptions.ArrayIndexOutOfBoundsException;
import org.rumbledb.exceptions.OurBadException;
import org.rumbledb.exceptions.UnexpectedTypeException;
import org.rumbledb.items.ItemFactory;
import org.rumbledb.runtime.AbstractAtMostOneItemRuntimePlan;

public class ArrayTailFunctionIterator extends AbstractAtMostOneItemRuntimePlan {

    @Serial
    private static final long serialVersionUID = 1L;

    private final RuntimePlan<Item> arrayIterator;

    public ArrayTailFunctionIterator(
            List<RuntimePlan<Item>> arguments,
            RuntimeStaticContext staticContext
    ) {
        super(arguments, staticContext);
        if (arguments.size() != 1) {
            throw new OurBadException("array:tail must have exactly one argument.");
        }
        this.arrayIterator = arguments.get(0);
    }


    @Override
    public Item evaluateAtMostOne(DynamicContext context) {
        return tailArgument(this.arrayIterator.materialize(context));
    }

    private Item tail(Item arrayItem) {
        if (arrayItem == null) {
            return null;
        }
        if (!arrayItem.isArray()) {
            throw new UnexpectedTypeException(
                    "Type error; argument to array:tail must be an array.",
                    getMetadata()
            );
        }

        int size = arrayItem.getSize();
        if (size == 0) {
            throw new ArrayIndexOutOfBoundsException(
                    "array:tail called on an empty array.",
                    getMetadata()
            );
        }

        if (size == 1) {
            return ItemFactory.getInstance()
                .createArrayItem(Collections.emptyList(), false);
        }

        if (arrayItem.isArrayOfItems()) {
            List<Item> originalMembers = arrayItem.getItemMembers();
            List<Item> tailMembers = new ArrayList<>(originalMembers.subList(1, size));
            return ItemFactory.getInstance()
                .createArrayItem(tailMembers, this.getRuntimeStaticContext().isQuerySideEffecting());
        } else {
            List<List<Item>> originalMembers = arrayItem.getSequenceMembers();
            List<List<Item>> tailMembers = new ArrayList<>(originalMembers.subList(1, size));
            return ItemFactory.getInstance()
                .createSequenceArrayItem(tailMembers, this.getRuntimeStaticContext().isQuerySideEffecting());
        }
    }

    private Item tailArgument(List<Item> items) {
        if (items.size() > 1) {
            throw new UnexpectedTypeException(
                    "array:tail expects exactly one array argument.",
                    getMetadata()
            );
        }
        return tail(items.isEmpty() ? null : items.get(0));
    }
}
