(:JIQS: ShouldRun; Output="(1, 2.14, 1, 3.4, 230004, 30000, aa, false, true, null, false, 30000, 3, 3, true, null, null, null, null, null, AABBCC, 0 FB8 0F+9, Q Q = =)" :)
1 cast as integer,
2.14 cast as decimal,
1 cast as decimal,
3.4 cast as double,
(4 + 2.3e5) cast as decimal,
3e4 cast as integer,
"aa" cast as string,
false cast as boolean,
2 cast as boolean,
null cast as string?,
() cast as string?,
"false" cast as boolean,
"3e4" cast as double,
"3" cast as decimal,
3 cast as string,
3.4 cast as boolean,
null cast as null,
null cast as null?,
"null" cast as null,
"null" cast as null?,
null cast as string,
"aabbCC" cast as hexBinary,
"0 FB8 0F+9" cast as base64Binary,
"Q Q = =" cast as base64Binary

(: general tests :)