(:JIQS: ShouldRun; Output="(true, true, true, true, true, true, false, true, false, true, true, true, true, false, true, true, true, true, true, true, true, true, true, false, true, false, false, true, true, true, true, false, true, true, true, false, true, false, false, true, true, false, false)" :)
1 castable as integer,
2.14 castable as decimal,
1 castable as decimal,
3.4 castable as double,
(4 + 2.3e5) castable as decimal,
3e4 castable as integer,
"aa" castable as integer,
"aa" castable as string,
(1,2,3) castable as integer,
false castable as boolean,
2 castable as boolean,
null castable as string?,
() castable as string?,
() castable as string,
"false" castable as boolean,
"3e4" castable as double,
"3" castable as decimal,
3 castable as string,
3.4 castable as boolean,
null castable as null,
null castable as null?,
"null" castable as null,
"null" castable as null?,
3 castable as null,
null castable as string,
null castable as integer?,
"foo" castable as null,
"P3Y8M" castable as duration,
yearMonthDuration("P2Y4M") castable as string,
yearMonthDuration("P2Y99M") castable as duration,
"-P6Y18M" castable as yearMonthDuration,
yearMonthDuration("P0Y0M") castable as dayTimeDuration,
dayTimeDuration("P3DT5H6.001S") castable as string,
dayTimeDuration("P3DT432H") castable as duration,
"-P4DT5M" castable as dayTimeDuration,
dayTimeDuration("PT0S") castable as yearMonthDuration,
"aabbCC" castable as hexBinary,
"123" castable as hexBinary,
"lmno" castable as hexBinary,
"0 FB8 0F+9" castable as base64Binary,
"Q Q = =" castable as base64Binary,
"1A3" castable as base64Binary,
"Q===" castable as base64Binary

(: general tests :)