(:JIQS: ShouldRun; Output="(true, true, true, true, true, true, false, true, false, true, true, true, true, false, true, true, true, true, true, true, true, true, true, false, true, false, false, true, false, false, true, true, true, false, false)" :)
1 castable as integer,
2.14 castable as decimal,
1 castable as decimal,
3.4 castable as double,
(4 + 2.3e5) castable as decimal,
3e4 castable as integer,
"aa" castable as integer,
"aa" castable as string,
(1,2,3) castable as integer,
false castable as boolean,
2 castable as boolean,
null castable as string?,
() castable as string?,
() castable as string,
"false" castable as boolean,
"3e4" castable as double,
"3" castable as decimal,
3 castable as string,
3.4 castable as boolean,
null castable as null,
null castable as null?,
"null" castable as null,
"null" castable as null?,
3 castable as null,
null castable as string,
null castable as integer?,
"foo" castable as null,
"aabbCC" castable as hexBinary,
"123" castable as hexBinary,
"lmno" castable as hexBinary,
"P3Y8M" castable as duration,
"0 FB8 0F+9" castable as base64Binary,
"Q Q = =" castable as base64Binary,
"1A3" castable as base64Binary,
"Q===" castable as base64Binary

(: general tests :)