(:JIQS: ShouldRun; Output="(true, true, true, false, false, true, true, true, true, false, false, true, false, false, false, true, true, false, true, true, false, true, true, false, false, true)" :)
1 instance of integer,
2.14 instance of decimal,
1 instance of decimal,
3.4 instance of double,
"aa" instance of integer,
"aa" instance of string+,
1 instance of item,
{"a": "b"} instance of object,
(1,2,3) instance of integer*,
("aa", 1) instance of string*,
(4 + 2.3e5) instance of decimal,
false instance of boolean,
2 instance of boolean,
null instance of string?,
null instance of string,
null instance of null,
null instance of null?,
[1,23,3] instance of integer+,
[1,23,3] instance of array,
({"aa": "bb"}, {"cc": "dd"}) instance of json-item+,
3 instance of (),
() instance of string?,
() instance of string*,
() instance of string+,
() instance of string,
() instance of ()

(: general tests :)

