/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Authors: Matteo Agnoletto (EPMatt)
 *
 */

package org.rumbledb.runtime.xml;

import org.rumbledb.api.Item;
import org.rumbledb.context.DynamicContext;
import org.rumbledb.context.RuntimeStaticContext;
import org.rumbledb.exceptions.AttributeOrNamespaceAfterNonAttributeException;
import org.rumbledb.exceptions.PredefinedPrefixInNamespaceDeclarationException;
import org.rumbledb.items.ItemFactory;
import org.rumbledb.items.xml.ElementItem;
import org.rumbledb.runtime.AtMostOneItemLocalRuntimeIterator;
import org.rumbledb.runtime.RuntimeIterator;

import java.util.ArrayList;
import java.util.List;

/**
 * Runtime iterator for direct element constructors.
 * 
 * @see org.rumbledb.expressions.xml.DirElemConstructorExpression
 */
public class DirElemConstructorRuntimeIterator extends AtMostOneItemLocalRuntimeIterator {

    private static final long serialVersionUID = 1L;
    private static final String XML_NAMESPACE_URI = "http://www.w3.org/XML/1998/namespace";
    private static final String XMLNS_NAMESPACE_URI = "http://www.w3.org/2000/xmlns/";
    private String tagName;
    private List<RuntimeIterator> content;
    private List<AttributeNodeRuntimeIterator> attributes;

    public DirElemConstructorRuntimeIterator(
            String tagName,
            List<RuntimeIterator> content,
            List<AttributeNodeRuntimeIterator> attributes,
            RuntimeStaticContext staticContext
    ) {
        super(createChildList(content, attributes), staticContext);
        this.content = content;
        this.attributes = attributes;
        this.tagName = tagName;
    }

    @Override
    public Item materializeFirstItemOrNull(DynamicContext dynamicContext) {
        // Check if this is the top-level runtime iterator for XML tree building
        DynamicContext contextToUse;
        if (dynamicContext.getTopLevelRuntimeIterator() == null) {
            // This is the top-level runtime iterator - create a new context and set this iterator as top-level
            contextToUse = new DynamicContext(dynamicContext);
            contextToUse.setTopLevelRuntimeIterator(this);
        } else {
            // A top-level iterator is already set - use the provided context
            contextToUse = dynamicContext;
        }

        List<Item> content = new ArrayList<>();
        List<Item> attributes = new ArrayList<>();
        List<Item> namespaces = new ArrayList<>();
        // process all child content
        if (this.content != null) {
            StringBuilder textAccumulator = null;
            boolean hasSeenNonAttributeNode = false;

            for (RuntimeIterator iterator : this.content) {
                iterator.open(contextToUse);
                while (iterator.hasNext()) {
                    Item item = iterator.next();

                    if (item.isAttributeNode() || item.isNamespaceNode()) {
                        if (hasSeenNonAttributeNode) {
                            throw new AttributeOrNamespaceAfterNonAttributeException(
                                    "Attribute or namespace nodes must appear before all other nodes in element content"
                            );
                        }
                        if (item.isAttributeNode()) {
                            attributes.add(item);
                        } else {
                            namespaces.add(item);
                        }
                        continue;
                    }

                    // check if this item should be treated as text content
                    // both proper text nodes, or any non-node items (e.g. generated by enclosed expressions) are
                    // treated as text nodes in the context of a direct element constructor.
                    if (item.isTextNode() || !item.isNode()) {
                        String textContent;
                        if (item.isTextNode()) {
                            textContent = item.getTextValue();
                        } else {
                            // non-node item - convert to string
                            textContent = item.getStringValue();
                        }

                        // skip empty text content according to XML spec
                        if (textContent.isEmpty()) {
                            continue;
                        }

                        if (textAccumulator == null) {
                            // start accumulating text content
                            textAccumulator = new StringBuilder();
                        }

                        // accumulate the text content
                        textAccumulator.append(textContent);
                        hasSeenNonAttributeNode = true;
                    } else {
                        hasSeenNonAttributeNode = true;
                        // non-text node encountered
                        if (textAccumulator != null) {
                            // finalize any accumulated text content
                            content.add(
                                ItemFactory.getInstance()
                                    .createXmlTextNode(
                                        textAccumulator.toString()
                                    )
                            );
                            textAccumulator = null;
                        }

                        // add the non-text node
                        content.add(item);
                    }
                }
                iterator.close();
            }

            // handle any remaining accumulated text at the end
            if (textAccumulator != null) {
                hasSeenNonAttributeNode = true;
                content.add(
                    ItemFactory.getInstance()
                        .createXmlTextNode(
                            textAccumulator.toString()
                        )
                );
            }
        }
        // process attributes
        if (this.attributes != null) {
            for (RuntimeIterator iterator : this.attributes) {
                iterator.open(contextToUse);
                while (iterator.hasNext()) {
                    Item item = iterator.next();

                    // attributes should be attribute nodes
                    if (item.isAttributeNode()) {
                        String[] namespaceBinding = parseNamespaceDeclarationAttribute(item);
                        if (namespaceBinding != null) {
                            String prefix = namespaceBinding[0];
                            String uri = namespaceBinding[1];
                            validateNamespaceDeclaration(prefix, uri);
                            namespaces.add(
                                ItemFactory.getInstance()
                                    .createXmlNamespaceNode(prefix, uri)
                            );
                        } else {
                            attributes.add(item);
                        }
                    }
                }
                iterator.close();
            }
        }
        // create and return the element item
        this.hasNext = false;
        ElementItem elementItem = (ElementItem) ItemFactory.getInstance()
            .createXmlElementNode(
                this.tagName,
                content,
                attributes
            );
        // Only add namespaces explicitly declared on this element
        for (Item namespace : namespaces) {
            elementItem.addOrReplaceNamespace(namespace);
        }
        // set the parent of the child nodes to the element node
        elementItem.addParentToDescendants();

        // Set XML document position if this is the top-level runtime iterator
        if (dynamicContext.getTopLevelRuntimeIterator() == null) {
            // This is the top-level runtime iterator - set XML document positions recursively
            // Use the hash code of the runtime iterator object as the path to track the identity of constructed objects
            String documentPath = String.valueOf(this.hashCode());
            elementItem.setXmlDocumentPosition(documentPath, 0);
        }

        return elementItem;
    }

    private static List<RuntimeIterator> createChildList(
            List<RuntimeIterator> content,
            List<AttributeNodeRuntimeIterator> attributes
    ) {
        List<RuntimeIterator> children = new ArrayList<>();
        // first add attributes, then content
        children.addAll(attributes);
        children.addAll(content);
        return children;
    }

    private static String[] parseNamespaceDeclarationAttribute(Item attributeItem) {
        if (!attributeItem.isAttributeNode()) {
            return null;
        }
        String attributeName = attributeItem.nodeName();
        if ("xmlns".equals(attributeName)) {
            return new String[] { "", attributeItem.getStringValue() };
        }
        if (attributeName.startsWith("xmlns:")) {
            String prefix = attributeName.substring("xmlns:".length());
            return new String[] { prefix, attributeItem.getStringValue() };
        }
        return null;
    }

    private static void validateNamespaceDeclaration(String prefix, String uri) {
        // Spec (https://www.w3.org/TR/xquery-31/#id-element-constructor):
        // "However, note that namespace declaration attributes (see 3.9.1.2 Namespace Declaration Attributes) do not
        // create attribute nodes."
        // "[Definition: A namespace declaration attribute is used inside a direct element constructor. Its purpose is
        // to bind a namespace prefix or to set the default element/type namespace for the constructed element node,
        // including its attributes.] Syntactically, a namespace declaration attribute has the form of an attribute
        // with namespace prefix xmlns, or with name xmlns and no namespace prefix."
        // "If the prefix of the attribute name is xmlns, then the local part of the attribute name is interpreted as a
        // namespace prefix."
        // "If the name of the namespace declaration attribute is xmlns with no prefix, then the namespace URI specifies
        // the default element/type namespace of the constructor expression (overriding any existing default), and is
        // added (with no prefix) to the in-scope namespaces of the constructed element (overriding any existing
        // namespace binding with no prefix)."
        // "It is a static error [err:XQST0070] if a namespace declaration attribute attempts to do any of the
        // following:"
        // Bind the prefix xml to some namespace URI other than http://www.w3.org/XML/1998/namespace.
        if ("xml".equals(prefix) && !XML_NAMESPACE_URI.equals(uri)) {
            throw new PredefinedPrefixInNamespaceDeclarationException(
                    "Namespace declaration attribute cannot bind the prefix xml to a non-XML namespace URI."
            );
        }
        // Bind the prefix xmlns to any namespace URI.
        if ("xmlns".equals(prefix)) {
            throw new PredefinedPrefixInNamespaceDeclarationException(
                    "Namespace declaration attribute cannot bind the prefix xmlns."
            );
        }
        // Bind a prefix other than xml to the namespace URI http://www.w3.org/XML/1998/namespace.
        if (!"xml".equals(prefix) && XML_NAMESPACE_URI.equals(uri)) {
            throw new PredefinedPrefixInNamespaceDeclarationException(
                    "Namespace declaration attribute cannot bind a non-xml prefix to the XML namespace URI."
            );
        }
        // Bind a prefix to the namespace URI http://www.w3.org/2000/xmlns/.
        if (XMLNS_NAMESPACE_URI.equals(uri)) {
            throw new PredefinedPrefixInNamespaceDeclarationException(
                    "Namespace declaration attribute cannot bind any prefix to the xmlns namespace URI."
            );
        }
        // TODO: handle binding a prefix to a zero-length namespace URI
    }

}
