(:JIQS: ShouldRun; Output="(true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false)" :)
anyURI("mailto:rumble") castable as string,
anyURI("mailto:rumble") castable as anyURI,
"mailto:rumble" castable as anyURI,
"mailto:" castable as anyURI,
anyURI("mailto:rumble") castable as integer,
anyURI(" mailto:rumble") castable as boolean,
anyURI("mailto:rumble  ") castable as duration,
anyURI("mailto:rumble ") castable as time,
anyURI("mailto:rumble") castable as hexBinary,
anyURI("mailto:rumble") castable as decimal,
anyURI("mailto:rumble") castable as double,
anyURI("mailto:rumble") castable as yearMonthDuration,
anyURI("mailto:rumble") castable as dayTimeDuration,
anyURI("mailto:rumble") castable as base64Binary,
anyURI("mailto:rumble") castable as dateTime,
anyURI("mailto:rumble") castable as date
