(:JIQS: ShouldRun; Output="(a, b, c, d, e, f, g, h, a, a, a, a, a, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)" :)
{"for" : "a"}.for,
{"let" : "b"}.let,
{"where" : "c"}.where,
{"group" : "d"}.group,
{"by" : "e"}.by,
{"order" : "f"}.order,
{"return" : "g"}.return,
{"if" : "h"}.if,
{"in" : "a"}.in,
{"as" : "a"}.as,
{"at" : "a"}.at,
{"allowing" : "a"}.allowing,
{"empty" : "a"}.empty,
{"count" : "1"}.count,
{"ascending" : "2"}.ascending,
{"descending" : "3"}.descending,
{"some" : "4"}.some,
{"every" : "5"}.every,
{"satisfies" : "6"}.satisfies,
{"collation" : "7"}.collation,
{"greatest" : "8"}.greatest,
{"least" : "9"}.least,
{"switch" : "10"}.switch,
{"case" : "11"}.case,
{"try" : "12"}.try,
{"catch" : "13"}.catch,
{"default" : "14"}.default,
{"then" : "15"}.then,
{"else" : "16"}.else



