/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.rumbledb.runtime.primary;

import org.rumbledb.api.Item;
import org.rumbledb.context.DynamicContext;
import org.rumbledb.context.RuntimeStaticContext;
import org.rumbledb.items.ItemFactory;
import org.rumbledb.runtime.AtMostOneItemLocalRuntimeIterator;
import org.rumbledb.runtime.RuntimeIterator;

import java.util.ArrayList;
import java.util.List;

public class DirElemConstructorRuntimeIterator extends AtMostOneItemLocalRuntimeIterator {

    private static final long serialVersionUID = 1L;
    private String tagName;
    private List<RuntimeIterator> children;
    private List<RuntimeIterator> attributes;

    public DirElemConstructorRuntimeIterator(
            String tagName,
            List<RuntimeIterator> children,
            List<RuntimeIterator> attributes,
            RuntimeStaticContext staticContext
    ) {
        super(children, staticContext); // TODO: is this correct? or should we pass children and attributes?
        this.children = children;
        this.attributes = attributes;
        this.tagName = tagName;
    }

    @Override
    public Item materializeFirstItemOrNull(DynamicContext dynamicContext) {
        List<Item> content = new ArrayList<>();
        List<Item> attributes = new ArrayList<>();
        // process all child content
        if (this.children != null) {
            StringBuilder textAccumulator = null;
            
            for (RuntimeIterator iterator : this.children) {
                iterator.open(dynamicContext);
                while (iterator.hasNext()) {
                    Item item = iterator.next();
                    
                    // check if this item should be treated as text content
                    // both proper text nodes, or any non-node items (e.g. generated by enclosed expressions) are
                    // treated as text nodes in the context of a direct element constructor.
                    if (item.isTextNode() || !item.isNode()) {
                        String textContent;
                        if (item.isTextNode()) {
                            textContent = item.getTextValue();
                        } else {
                            // non-node item - convert to string
                            textContent = item.getStringValue();
                        }
                        
                        // skip empty text content according to XML spec
                        if (textContent.isEmpty()) {
                            continue;
                        }
                        
                        if (textAccumulator == null) {
                            // start accumulating text content
                            textAccumulator = new StringBuilder();
                        }
                        
                        // accumulate the text content
                        textAccumulator.append(textContent);
                    } else {
                        // non-text node encountered
                        if (textAccumulator != null) {
                            // finalize any accumulated text content
                            content.add(ItemFactory.getInstance().createXmlTextNode(
                                textAccumulator.toString()
                            ));
                            textAccumulator = null;
                        }
                        
                        // add the non-text node
                        content.add(item);
                    }
                }
                iterator.close();
            }
            
            // handle any remaining accumulated text at the end
            if (textAccumulator != null) {
                content.add(ItemFactory.getInstance().createXmlTextNode(
                    textAccumulator.toString()
                ));
            }
        }
        // create and return the element item
        this.hasNext = false;
        return ItemFactory.getInstance()
            .createXmlElementNode(
                this.tagName,
                content,
                attributes
            );
    }
}
