/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.rumbledb.config.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.KryoSerializable;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.Singular;
import lombok.Value;
import lombok.experimental.Accessors;
import lombok.experimental.NonFinal;
import lombok.extern.jackson.Jacksonized;

@Value
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder(toBuilder = true)
@Jacksonized
@Accessors(fluent = true)
public class AccessConfig implements Serializable, KryoSerializable {
    private static final long serialVersionUID = 1L;

    /**
     * Allowed URI prefixes for read/write (with I/O functions to read data)
     */
    @NonFinal
    @Singular
    private List<String> allowedPrefixes;

    @Override
    public void write(Kryo kryo, Output output) {
        if (this.allowedPrefixes == null) {
            output.writeInt(-1);
            return;
        }
        output.writeInt(this.allowedPrefixes.size());
        for (String allowedPrefix : this.allowedPrefixes) {
            output.writeString(allowedPrefix);
        }
    }

    @Override
    public void read(Kryo kryo, Input input) {
        int size = input.readInt();
        if (size < 0) {
            this.allowedPrefixes = null;
            return;
        }
        List<String> prefixes = new ArrayList<>(size);
        for (int i = 0; i < size; i++) {
            prefixes.add(input.readString());
        }
        this.allowedPrefixes = Collections.unmodifiableList(prefixes);
    }

    // Avoid Javadoc error because it cannot resolve the builder class generated by Lombok
    public static class AccessConfigBuilder {
    }
}
