/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.rumbledb.config.model;


import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.KryoSerializable;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.NoArgsConstructor;
import lombok.Value;
import lombok.experimental.Accessors;
import lombok.experimental.NonFinal;
import lombok.extern.jackson.Jacksonized;

@Value
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder(toBuilder = true)
@Jacksonized
@Accessors(fluent = true)
public class InputConfig implements KryoSerializable {
    /**
     * Path from which the JSONiq or XQuery query is to be read.
     */
    @NonFinal
    private String queryPath;

    /**
     * Query that was passed from the command line
     * (This should be removed later when we have separate classes for CLI and API)
     */
    @NonFinal
    private String query;

    @Override
    public void write(Kryo kryo, Output output) {
        output.writeString(this.queryPath);
        output.writeString(this.query);
    }

    @Override
    public void read(Kryo kryo, Input input) {
        this.queryPath = input.readString();
        this.query = input.readString();
    }

    // Avoid Javadoc error because it cannot resolve the builder class generated by Lombok
    public static class InputConfigBuilder {
    }
}
