/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.rumbledb.config.model;


import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.KryoSerializable;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Builder.Default;
import lombok.NoArgsConstructor;
import lombok.Value;
import lombok.experimental.Accessors;
import lombok.experimental.NonFinal;
import lombok.extern.jackson.Jacksonized;

@Value
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder(toBuilder = true)
@Jacksonized
@Accessors(fluent = true)
public class OptimizationConfig implements KryoSerializable {
    /**
     * Whether function inlining is enabled.
     */
    @NonFinal
    @Default
    private boolean useFunctionInlining = true;

    /**
     * Whether tail call optimization is enabled.
     */
    @NonFinal
    @Default
    private boolean useTailCallOptimization = true;

    /**
     * Whether general comparisons may be rewritten using value comparisons.
     */
    @NonFinal
    @Default
    private boolean optimizeGeneralComparisonToValueComparison = true;

    /**
     * Whether XPath steps should be optimized.
     */
    @NonFinal
    @Default
    private boolean optimizeSteps = true;

    /**
     * Whether XPath steps should be optimized including experimental algorithms.
     */
    @NonFinal
    @Default
    private boolean optimizeStepsExperimental = false;

    /**
     * Whether parent pointers can be optimized away in XPath expressions.
     */
    @NonFinal
    @Default
    private boolean optimizeParentPointers = true;

    @Override
    public void write(Kryo kryo, Output output) {
        output.writeBoolean(this.useFunctionInlining);
        output.writeBoolean(this.useTailCallOptimization);
        output.writeBoolean(this.optimizeGeneralComparisonToValueComparison);
        output.writeBoolean(this.optimizeSteps);
        output.writeBoolean(this.optimizeStepsExperimental);
        output.writeBoolean(this.optimizeParentPointers);
    }

    @Override
    public void read(Kryo kryo, Input input) {
        this.useFunctionInlining = input.readBoolean();
        this.useTailCallOptimization = input.readBoolean();
        this.optimizeGeneralComparisonToValueComparison = input.readBoolean();
        this.optimizeSteps = input.readBoolean();
        this.optimizeStepsExperimental = input.readBoolean();
        this.optimizeParentPointers = input.readBoolean();
    }

    // Avoid Javadoc error because it cannot resolve the builder class generated by Lombok
    public static class OptimizationConfigBuilder {
    }
}
