/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.rumbledb.config.model;



import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.KryoSerializable;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import org.rumbledb.serialization.SerializationParameters;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Builder.Default;
import lombok.NoArgsConstructor;
import lombok.Value;
import lombok.experimental.Accessors;
import lombok.experimental.NonFinal;
import lombok.extern.jackson.Jacksonized;

@Value
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder(toBuilder = true)
@Jacksonized
@Accessors(fluent = true)
public class OutputConfig implements KryoSerializable {
    public static final int DEFAULT_NUMBER_OF_OUTPUT_PARTITIONS = -1;

    /**
     * Number of output partitions to write to the output path.
     */
    @NonFinal
    @Default
    private int numberOfOutputPartitions = DEFAULT_NUMBER_OF_OUTPUT_PARTITIONS;

    /**
     * Path to which the output path should be written.
     */
    @NonFinal
    private String outputPath;

    /**
     * Output format for writing to the output path.
     */
    @NonFinal
    private String outputFormat;

    /**
     * Whether to overwrite the output path if it already exists.
     */
    @NonFinal
    @Default
    private boolean allowOverwrite = false;

    /**
     * Options to further specify the output format, for example a separator character for CSV or a compression format.
     */
    @NonFinal
    private SerializationParameters serializationParameters;

    /**
     * Log path
     */
    @NonFinal
    private String logPath;

    /**
     * Current shell filter for post-processing output (e.g. JSON beautifier)
     */
    @NonFinal
    private String shellFilter;

    @Override
    public void write(Kryo kryo, Output output) {
        output.writeInt(this.numberOfOutputPartitions);
        output.writeString(this.outputPath);
        output.writeString(this.outputFormat);
        output.writeBoolean(this.allowOverwrite);
        kryo.writeClassAndObject(output, this.serializationParameters);
        output.writeString(this.logPath);
        output.writeString(this.shellFilter);
    }

    @Override
    public void read(Kryo kryo, Input input) {
        this.numberOfOutputPartitions = input.readInt();
        this.outputPath = input.readString();
        this.outputFormat = input.readString();
        this.allowOverwrite = input.readBoolean();
        this.serializationParameters = (SerializationParameters) kryo.readClassAndObject(input);
        this.logPath = input.readString();
        this.shellFilter = input.readString();
    }

    // Avoid Javadoc error because it cannot resolve the builder class generated by Lombok
    public static class OutputConfigBuilder {
    }
}
