/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package org.rumbledb.config.model;


import java.io.Serializable;

import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.KryoSerializable;
import com.esotericsoftware.kryo.io.Input;
import com.esotericsoftware.kryo.io.Output;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Builder.Default;
import lombok.NoArgsConstructor;
import lombok.Value;
import lombok.experimental.Accessors;
import lombok.experimental.NonFinal;
import lombok.extern.jackson.Jacksonized;

@Value
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder(toBuilder = true)
@Jacksonized
@Accessors(fluent = true)
public class RuntimeConfig implements Serializable, KryoSerializable {
    private static final long serialVersionUID = 1L;

    public static final int DEFAULT_RESULTS_SIZE_CAP = 10;
    public static final int DEFAULT_MATERIALIZATION_CAP = 100000;

    @NonFinal
    @Default
    private int resultsSizeCap = DEFAULT_RESULTS_SIZE_CAP;

    @NonFinal
    @Default
    private int materializationCap = DEFAULT_MATERIALIZATION_CAP;

    @NonFinal
    @Default
    private boolean useNativeSQLPredicates = true;

    @NonFinal
    @Default
    private boolean detectDataFrameExecutionMode = true;

    @NonFinal
    @Default
    private boolean useParallelExecution = true;

    @NonFinal
    @Default
    private boolean useDataFrameExecution = true;

    @NonFinal
    @Default
    private boolean useNativeExecution = true;

    @NonFinal
    @Default
    private boolean shouldApplyUpdates = false;

    @Override
    public void write(Kryo kryo, Output output) {
        output.writeInt(this.resultsSizeCap);
        output.writeInt(this.materializationCap);
        output.writeBoolean(this.useNativeSQLPredicates);
        output.writeBoolean(this.detectDataFrameExecutionMode);
        output.writeBoolean(this.useParallelExecution);
        output.writeBoolean(this.useDataFrameExecution);
        output.writeBoolean(this.useNativeExecution);
        output.writeBoolean(this.shouldApplyUpdates);
    }

    @Override
    public void read(Kryo kryo, Input input) {
        this.resultsSizeCap = input.readInt();
        this.materializationCap = input.readInt();
        this.useNativeSQLPredicates = input.readBoolean();
        this.detectDataFrameExecutionMode = input.readBoolean();
        this.useParallelExecution = input.readBoolean();
        this.useDataFrameExecution = input.readBoolean();
        this.useNativeExecution = input.readBoolean();
        this.shouldApplyUpdates = input.readBoolean();
    }

    // Avoid Javadoc error because it cannot resolve the builder class generated by Lombok
    public static class RuntimeConfigBuilder {
    }
}
