name: Run QT3 Suite

on:
  workflow_dispatch:
  push:
    branches:
      - jimmy/thesis-baseline

jobs:
  qt3-jsoniq:
    uses: ./.github/workflows/qt3-suite.yml
    with:
      tested_parser: jsoniq
      mvn_args: ''
      run_analytics: true
  qt3-xquery:
    uses: ./.github/workflows/qt3-suite.yml
    with:
      tested_parser: xquery
      mvn_args: ''
      run_analytics: true
